#!/bin/bash
# ⚠️ DEPRECATED - This script is no longer needed
# Database initialization is now automatic via docker-compose and Spring Boot
#
# MSSQL Database Initialization Script (Legacy)
# Run this ONCE after first docker-compose up

echo "Waiting for MSSQL to be ready..."
until docker exec pet-mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Passw0rd" -Q "SELECT 1" &> /dev/null
do
  echo "MSSQL is starting up..."
  sleep 3
done

echo "MSSQL is ready! Creating databases..."

# Create Primary database
docker exec pet-mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Passw0rd" -Q "
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'petdb')
BEGIN
    CREATE DATABASE petdb;
    PRINT 'Database petdb created successfully';
END
ELSE
BEGIN
    PRINT 'Database petdb already exists';
END
"

# Create Log database
docker exec pet-mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Passw0rd" -Q "
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'petdb_log')
BEGIN
    CREATE DATABASE petdb_log;
    PRINT 'Database petdb_log created successfully';
END
ELSE
BEGIN
    PRINT 'Database petdb_log already exists';
END
"

echo ""
echo "========================================="
echo "📊 Primary DB (petdb) Setup"
echo "========================================="
echo "Importing schema to petdb..."
docker exec -i pet-mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Passw0rd' -d petdb < src/main/resources/db/schema-mssql.sql

echo "Importing test data to petdb..."
docker exec -i pet-mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Passw0rd' -d petdb < src/main/resources/db/data-mssql.sql

echo ""
echo "========================================="
echo "📝 Log DB (petdb_log) Setup"
echo "========================================="
echo "Log DB created (schema will be auto-generated by Hibernate with ddl-auto: update)"
echo "No test data imported to Log DB"

echo ""
echo "========================================="
echo "✅ All Done! Your databases are ready"
echo "========================================="
echo "📊 Primary DB: jdbc:sqlserver://localhost:1433;databaseName=petdb"
echo "📝 Log DB: jdbc:sqlserver://localhost:1433;databaseName=petdb_log"
echo "========================================="
